version: '3.1'

services:
  sub:
    build: .
    restart: always
    ports:
      - 3300:80
    volumes:
      - .:/var/www/html/
    environment:
      ENVIRONMENT: dev
  sub_db:
    image: mariadb:10.11
    restart: always
    ports:
      - 3706:3306
    environment:
      MARIADB_ROOT_PASSWORD: sub_root_password
      MARIADB_DATABASE: sub
      MARIADB_USER: sub_user
      MARIADB_PASSWORD: sub_password
