<?php

use App\Http\Controllers\MessageController;
use App\Http\Controllers\SubscriptionController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

// Authentication routes (generated by `php artisan make:auth`)
Auth::routes();

// Admin routes for sending messages
Route::middleware('auth')->group(function() {
    Route::get('/messages', [MessageController::class, 'index'])->name('messages.index');
    Route::post('/messages', [MessageController::class, 'send'])->name('messages.send');
});

// Twilio webhook for subscription
Route::post('/sms-subscribe', [SubscriptionController::class, 'subscribe']);
