version: '3.1'

services:
    sub:
        build: .
        restart: always
        ports:
            - 3200:80
        volumes:
            - ../src:/var/www/html/sub
    sub_db:
        image: mysql:5.7
        restart: always
        ports:
            - 3116:3306
        environment:
            MYSQL_ROOT_PASSWORD: sub_root_password
            MYSQL_DATABASE: sub_test
            MYSQL_USER: sub_user
            MYSQL_PASSWORD: sub_password
            MYSQL_ROOT_HOST: '%'
